name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    permissions:
      actions: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          all_but_latest: true

      - name: Clean SPM artifacts
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf .build
          rm -f LvL-up.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
          rm -rf Build/

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - uses: ruby/setup-ruby@v1

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Resolve Packages
        run: |
          xcodebuild -resolvePackageDependencies \
            -workspace "LvL-up.xcodeproj/project.xcworkspace" \
            -scheme "LvL-up" \
            -derivedDataPath Build \
            -scmProvider system \
            -disableAutomaticPackageResolution

      - name: Swift Packages Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('LvL-up.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-

      - name: Clear Cache
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Run Tests 
        run: bundle exec fastlane unit_test