name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    permissions:
      actions: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          all_but_latest: true

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      # 1. Оптимизированная очистка кеша
      - name: Clean workspace
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf .build
          rm -rf Build/
          # Не удаляем Package.resolved!

      # 2. Кеширование с правильными путями
      - name: Swift Packages Cache
        uses: actions/cache@v3
        id: spm-cache
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            .build
            Build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      # 3. Разрешение зависимостей с правильными параметрами
      - name: Resolve Packages
        run: |
          xcodebuild -resolvePackageDependencies \
            -workspace "LvL-up.xcodeproj/project.xcworkspace" \
            -scheme "LvL-up" \
            -derivedDataPath Build \
            -scmProvider system \
            -clonedSourcePackagesDirPath .build

      # 4. Запуск тестов с явными путями
      - name: Run Tests
        run: |
          bundle exec fastlane unit_test \
            derived_data_path:"$PWD/Build" \
            cloned_source_packages_dir_path:"$PWD/.build"